### ISSUE TITLE
 kazoo seko:00482 (mirliton)

### ISSUE THREAD

**Issue by jarmosaarikko** [jarmosaarikko/SEKO#15]
Note! several of the altLabels of **kazoo** ([seko:00482](http://urn.fi/urn:nbn:fi:au:seko:00482)) are separate instruments in Wikipedia/Wikidata.  - (bazoo, bazooka, eunuch flute, flûte à l'oignon, flûte eunuque, gazoo, gazooka, gazoota, kazoopilli, tommy talker, zarah, Zwiebelflöte)

These may need to be added?
- https://en.wikipedia.org/wiki/Kazoo
- https://en.wikipedia.org/wiki/Bazooka_(instrument)
- https://en.wikipedia.org/wiki/Eunuch_flute
- https://en.wiktionary.org/wiki/bazoo#English

**Comment by HeikkiPoroila** [comment]
Definitely we need at least three different entries: for "kazoo", "bazooka" and "eunuch flute", which are all clearly different instruments. The most problematic might be the "eunuck flute", since it does not seem to be easy to decide, which term should be used in SEKO in the first place. Both French and Deutsch Wikipedia use the general term "mirliton". The Finnish translation "eunukkihuilu" sounds irrelevant, but maybe "flûte à l'oignon" would be a better one.

**Comment by jarmosaarikko** [comment]
siirretään ohjaustermit zwiebelflöte, flûte à l'oignon, flûte eunuque KÄYTÄ mirliton
bazooka, gazooka,   voidaan lisätä sanastoon, mutta vaskipuhaltimien alle uutena käsitteenä.
